### PR TITLE
`guide.lua, Line: 748, Error: NYI: bytecode UCLO  , Count: 233`

### PR DESCRIPTION
**Pull request by tmillr**

### CODE REVIEW

**Comment by CppCXY** [comment]
I think fixing all the jitfail code to make it compatible with LuaJIT is very difficult, and even after modifying several parts, I still don't see any significant performance improvement. Additionally, LuaJIT's runtime memory usage has increased by 10%. I don't think migrating to LuaJIT is very meaningful anymore.

**Comment by CppCXY** [comment]
I plan to revert the code to support Lua 5.4 and synchronize updates with LuaLS. The LuaJIT version will be retained as a separate branch.

**Comment by CppCXY** [comment]
I think instead of struggling with LuaJIT, it would be better to rewrite the language server in a native language.

**Comment by tmillr** [comment]
> I think instead of struggling with LuaJIT, it would be better to rewrite the language server in a native language.

Yeah you're probably right. It could be a similar amount of work either way, but you'll get more bang for your buck replacing the hottest paths with native functions. Perhaps rewriting all the parser logic first would be a good start?

**Comment by CppCXY** [comment]
> > I think instead of struggling with LuaJIT, it would be better to rewrite the language server in a native language.
> 
> Yeah you're probably right. It could be a similar amount of work either way, but you'll get more bang for your buck replacing the hottest paths with native functions. Perhaps rewriting all the parser logic first would be a good start?

sumneko is working on his 4.0 version, so it doesn't make much sense for me to rewrite parser now. Besides, I also have my own language server to maintain. I'll consider it after the 4.0 version is released

**Pull request closed without merging**
